export const GET_ACCOUNTID_FAIL = "GET_ACCOUNTID_FAIL";
export const GET_ACCOUNTID_SUCCESS = "GET_ACCOUNTID_SUCCESS";
export const GET_ACCOUNTID_REQUEST = "GET_ACCOUNTID_REQUEST";
export const GET_ACCOUNTID_RESET = "GET_ACCOUNTID_RESET";

export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

export const CHANGE_INFOR_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_INFOR_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_INFOR_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_INFOR_RESET = "CHANGE_PASSWORD_RESET";