export const GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_REQUEST = "GET_ACCOUNT_REQUEST";
export const GET_ACCOUNT_RESET = "GET_ACCOUNT_RESET";

export const GET_GENRE_FAIL = "GET_GENRE_FAIL";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const GET_GENRE_REQUEST = "GET_GENRE_REQUEST";
export const GET_GENRE_RESET = "GET_GENRE_RESET";
//order
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_RESET = "GET_ORDER_RESET";

export const ADD_GENRE_FAIL = "ADD_GENRE_FAIL";
export const ADD_GENRE_SUCCESS = "ADD_GENRE_SUCCESS";
export const ADD_GENRE_REQUEST = "ADD_GENRE_REQUEST";
export const ADD_GENRE_RESET = "ADD_GENRE_RESET";


export const UPDATE_GENRE_FAIL = "UPDATE_GENRE_FAIL";
export const UPDATE_GENRE_SUCCESS = "UPDATE_GENRE_SUCCESS";
export const UPDATE_GENRE_REQUEST = "UPDATE_GENRE_REQUEST";
export const UPDATE_GENRE_RESET = "UPDATE_GENRE_RESET";

