export const GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_REQUEST = "GET_ACCOUNT_REQUEST";
export const GET_ACCOUNT_RESET = "GET_ACCOUNT_RESET";

export const GET_GENRE_FAIL = "GET_GENRE_FAIL";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const GET_GENRE_REQUEST = "GET_GENRE_REQUEST";
export const GET_GENRE_RESET = "GET_GENRE_RESET";
//order
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_RESET = "GET_ORDER_RESET";