export const GET_COMPETITION_MODERATOR_REQUEST = "GET_COMPETITION_MODERATOR_REQUEST";
export const GET_COMPETITION_MODERATOR_SUCCESS = "GET_COMPETITION_MODERATOR_SUCCESS";
export const GET_COMPETITION_MODERATOR_FAIL = "GET_COMPETITION_MODERATOR_FAIL";
export const GET_COMPETITION_MODERATOR_RESET = "GET_COMPETITION_MODERATOR_RESET";