export const GET_COMPETITION_MODERATOR_REQUEST = "GET_COMPETITION_MODERATOR_REQUEST";
export const GET_COMPETITION_MODERATOR_SUCCESS = "GET_COMPETITION_MODERATOR_SUCCESS";
export const GET_COMPETITION_MODERATOR_FAIL = "GET_COMPETITION_MODERATOR_FAIL";
export const GET_COMPETITION_MODERATOR_RESET = "GET_COMPETITION_MODERATOR_RESET";

export const GET_COMPETITION_INFO_REQUEST = "GET_COMPETITION_INFO_REQUEST";
export const GET_COMPETITION_INFO_SUCCESS = "GET_COMPETITION_INFO_SUCCESS";
export const GET_COMPETITION_INFO_FAIL = "GET_COMPETITION_INFO_FAIL";
export const GET_COMPETITION_INFO_RESET = "GET_COMPETITION_INFO_RESET";

export const ADD_COMPETITION_FORMAT_REQUEST = "ADD_COMPETITION_FORMAT_REQUEST";
export const ADD_COMPETITION_FORMAT_SUCCESS = "ADD_COMPETITION_FORMAT_SUCCESS";
export const ADD_COMPETITION_FORMAT_FAIL = "ADD_COMPETITION_FORMAT_FAIL";
export const ADD_COMPETITION_FORMAT_RESET = "ADD_COMPETITION_FORMAT_RESET";

export const ACTIVE_COMPETITION_REQUEST = "ACTIVE_COMPETITION_REQUEST";
export const ACTIVE_COMPETITION_SUCCESS = "ACTIVE_COMPETITION_SUCCESS";
export const ACTIVE_COMPETITION_FAIL = "ACTIVE_COMPETITION_FAIL";
export const ACTIVE_COMPETITION_RESET = "ACTIVE_COMPETITION_RESET";