export const GET_CONTESTANT_REQUEST = "GET_CONTESTANT_REQUEST";
export const GET_CONTESTANT_SUCCESS = "GET_CONTESTANT_SUCCESS";
export const GET_CONTESTANT_FAIL = "GET_CONTESTANT_FAIL";
export const GET_CONTESTANT_RESET = "GET_CONTESTANT_RESET";