export const GET_CONTESTANT_REQUEST = "GET_CONTESTANT_REQUEST";
export const GET_CONTESTANT_SUCCESS = "GET_CONTESTANT_SUCCESS";
export const GET_CONTESTANT_FAIL = "GET_CONTESTANT_FAIL";
export const GET_CONTESTANT_RESET = "GET_CONTESTANT_RESET";

export const CREATE_CONTESTANT_REQUEST = "CREATE_CONTESTANT_REQUEST";
export const CREATE_CONTESTANT_SUCCESS = "CREATE_CONTESTANT_SUCCESS";
export const CREATE_CONTESTANT_FAIL = "CREATE_CONTESTANT_FAIL";
export const CREATE_CONTESTANT_RESET = "CREATE_CONTESTANT_RESET";