export const GET_ACTIVE_FORMAT_REQUEST = "GET_ACTIVE_FORMAT_REQUEST";
export const GET_ACTIVE_FORMAT_SUCCESS = "GET_ACTIVE_FORMAT_SUCCESS";
export const GET_ACTIVE_FORMAT_FAIL = "GET_ACTIVE_FORMAT_FAIL";
export const GET_ACTIVE_FORMAT_RESET = "GET_ACTIVE_FORMAT_RESET";