export const GET_REFEREE_REQUEST = "GET_REFEREE_REQUEST";
export const GET_REFEREE_SUCCESS = "GET_REFEREE_SUCCESS";
export const GET_REFEREE_FAIL = "GET_REFEREE_FAIL";
export const GET_REFEREE_RESET = "GET_REFEREE_RESET";

export const CREATE_REFEREE_REQUEST = "CREATE_REFEREE_REQUEST";
export const CREATE_REFEREE_SUCCESS = "CREATE_REFEREE_SUCCESS";
export const CREATE_REFEREE_FAIL = "CREATE_REFEREE_FAIL";
export const CREATE_REFEREE_RESET = "CREATE_REFEREE_RESET";