export const IMPORT_RULE_REQUEST = "IMPORT_RULE_REQUEST";
export const IMPORT_RULE_SUCCESS = "IMPORT_RULE_SUCCESS";
export const IMPORT_RULE_FAIL = "IMPORT_RULE_FAIL";
export const IMPORT_RULE_RESET = "IMPORT_RULE_RESET";