export const IMPORT_RULE_REQUEST = "IMPORT_RULE_REQUEST";
export const IMPORT_RULE_SUCCESS = "IMPORT_RULE_SUCCESS";
export const IMPORT_RULE_FAIL = "IMPORT_RULE_FAIL";
export const IMPORT_RULE_RESET = "IMPORT_RULE_RESET";

export const GET_RULE_REQUEST = "GET_RULE_REQUEST";
export const GET_RULE_SUCCESS = "GET_RULE_SUCCESS";
export const GET_RULE_FAIL = "GET_RULE_FAIL";
export const GET_RULE_RESET = "GET_RULE_RESET";