export const ADD_SCORE_REQUEST = "ADD_SCORE_REQUEST";
export const ADD_SCORE_SUCCESS = "ADD_SCORE_SUCCESS";
export const ADD_SCORE_FAIL = "ADD_SCORE_FAIL";
export const ADD_SCORE_RESET = "ADD_SCORE_RESET";

export const GET_SCORE_REQUEST = "GET_SCORE_REQUEST";
export const GET_SCORE_SUCCESS = "GET_SCORE_SUCCESS";
export const GET_SCORE_FAIL = "GET_SCORE_FAIL";
export const GET_SCORE_RESET = "GET_SCORE_RESET";