export const ADD_SCORE_REQUEST = "ADD_SCORE_REQUEST";
export const ADD_SCORE_SUCCESS = "ADD_SCORE_SUCCESS";
export const ADD_SCORE_FAIL = "ADD_SCORE_FAIL";
export const ADD_SCORE_RESET = "ADD_SCORE_RESET";