export const GET_TEAMS_REQUEST = "GET_TEAMS_REQUEST";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAIL = "GET_TEAMS_FAIL";
export const GET_TEAMS_RESET = "GET_TEAMS_RESET";

export const ADD_TEAM_KNOCKOUT_REQUEST = "ADD_TEAM_KNOCKOUT_REQUEST";
export const ADD_TEAM_KNOCKOUT_SUCCESS = "ADD_TEAM_KNOCKOUT_SUCCESS";
export const ADD_TEAM_KNOCKOUT_FAIL = "ADD_TEAM_KNOCKOUT_FAIL";
export const ADD_TEAM_KNOCKOUT_RESET = "ADD_TEAM_KNOCKOUT_RESET";


export const GET_TEAM_KNOCKOUT_REQUEST = "GET_TEAM_KNOCKOUT_REQUEST";
export const GET_TEAM_KNOCKOUT_SUCCESS = "GET_TEAM_KNOCKOUT_SUCCESS";
export const GET_TEAM_KNOCKOUT_FAIL = "GET_TEAM_KNOCKOUT_FAIL";
export const GET_TEAM_KNOCKOUT_RESET = "GET_TEAM_KNOCKOUT_RESET";

export const ADD_TEAM_TABLE_REQUEST = "ADD_TEAM_TABLE_REQUEST";
export const ADD_TEAM_TABLE_SUCCESS = "ADD_TEAM_TABLE_SUCCESS";
export const ADD_TEAM_TABLE_FAIL = "ADD_TEAM_TABLE_FAIL";
export const ADD_TEAM_TABLE_RESET = "ADD_TEAM_TABLE_RESET";

export const GET_TEAM_TABLE_REQUEST = "GET_TEAM_TABLE_REQUEST";
export const GET_TEAM_TABLE_SUCCESS = "GET_TEAM_TABLE_SUCCESS";
export const GET_TEAM_TABLE_FAIL = "GET_TEAM_TABLE_FAIL";
export const GET_TEAM_TABLE_RESET = "GET_TEAM_TABLE_RESET";

export const GET_TEAM_MATCH_GROUP_REQUEST = "GET_TEAM_MATCH_GROUP_REQUEST";
export const GET_TEAM_MATCH_GROUP_SUCCESS = "GET_TEAM_MATCH_GROUP_SUCCESS";
export const GET_TEAM_MATCH_GROUP_FAIL = "GET_TEAM_MATCH_GROUP_FAIL";
export const GET_TEAM_MATCH_GROUP_RESET = "GET_TEAM_MATCH_GROUP_RESET";