export const GET_TOURNAMENT_MODERATOR_REQUEST = "GET_TOURNAMENT_MODERATOR_REQUEST";
export const GET_TOURNAMENT_MODERATOR_SUCCESS = "GET_TOURNAMENT_MODERATOR_SUCCESS";
export const GET_TOURNAMENT_MODERATOR_FAIL = "GET_TOURNAMENT_MODERATOR_FAIL";
export const GET_TOURNAMENT_MODERATOR_RESET = "GET_TOURNAMENT_MODERATOR_RESET";