export const GET_TOURNAMENT_MODERATOR_REQUEST = "GET_TOURNAMENT_MODERATOR_REQUEST";
export const GET_TOURNAMENT_MODERATOR_SUCCESS = "GET_TOURNAMENT_MODERATOR_SUCCESS";
export const GET_TOURNAMENT_MODERATOR_FAIL = "GET_TOURNAMENT_MODERATOR_FAIL";
export const GET_TOURNAMENT_MODERATOR_RESET = "GET_TOURNAMENT_MODERATOR_RESET";

export const GET_TOURNAMENT_INFO_REQUEST = "GET_TOURNAMENT_INFO_REQUEST";
export const GET_TOURNAMENT_INFO_SUCCESS = "GET_TOURNAMENT_INFO_SUCCESS";
export const GET_TOURNAMENT_INFO_FAIL = "GET_TOURNAMENT_INFO_FAIL";
export const GET_TOURNAMENT_INFO_RESET = "GET_TOURNAMENT_INFO_RESET";